version: "3.8"

services:
  sql-server: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: "sql-server"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MySuperPassword123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - db_net
    # volumes:
    #   - mssql-server:/var/opt/mssql/data:r

  # docker-compose-api:
  #   build: .
  #   # environment:
  #   depends_on:
  #     - sql-server
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - db_net

networks:
  db_net:
    name: docker_compose_api_network
    driver: bridge


volumes:
  mssql-server: