version: "3.8"

services:
  sql-server: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: "sql-server"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MySuperPassword123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - db_net
    volumes:
      - mssql-server:/var/opt/mssql

  docker-compose-api:
    build: .
    environment:
      DB_SERVER: "sql-server"
      DB_PORT: "1433"
      DB_USER: "SA"
      DB_PASSWORD: "MySuperPassword123"
      DB_NAME: "Colors"
    depends_on:
      - sql-server
    ports:
      - "8080:80"
    networks:
      - db_net

networks:
  db_net:
    name: docker_compose_api_network
    driver: bridge


volumes:
  mssql-server: